{
 "title": "NGINX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(nginx_http_requests_total, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic : Requests / Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\"}[2m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\", cache_status!~\"MISS|NONE\"}[2m]))",
     "legendFormat": "Cached Resp"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\"}[2m])) - sum(rate(nginx_http_requests_total{cluster=~\"$cluster\", cache_status!~\"MISS|NONE\"}[2m]))",
     "legendFormat": "Nginx upstream"
    }
   ]
  },
  {
   "title": "Nginx Request Cache Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(nginx_http_requests_total[${__range_s}s])) by (cache_status))",
     "legendFormat": "{{ cache_status }}"
    }
   ]
  },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"4..|5..\"}[5m])) by (status,cache_status) / ignoring(status,cache_status) group_left sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status}} {{ cache_status }}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"2..|3..\"}[5m])) by (status,cache_status) / ignoring(status,cache_status) group_left sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status}} Cache:{{ cache_status }}"
    }
   ]
  },
  {
   "title": "Nginx Metrics error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_metric_errors_total", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}