{
 "title": "NGINX-New",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(nginx_http_requests_total, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic : Requests / Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{status!=\"444\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Valid Traffic"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{status=\"444\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Blocked Traffic Outside India"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Total Traffic"
    }
   ]
  },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!=\"444\",cluster=~\"$cluster\", status!~\"4..|5..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total{status!=\"444\",cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!=\"444\",cluster=~\"$cluster\", status!~\"2..|3..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total{status!=\"444\",cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}